version: '2'
services:

  postgres-data:
    image: busybox
    volumes:
        - /var/lib/postgresql/actcast-data
    container_name: actcast-postgres-datastore

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres-data
    volumes_from:
      - postgres-data
    volumes:
      - ./:/source

  postgrest:
    build: ./postgrest-docker
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://app_user:password@postgres:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
      PGRST_DB_POOL: 100
      PGRST_SERVER_HOST: "*4"
      PGRST_SERVER_PORT: 3000
      PGRST_SERVER_PROXY_URI: ""
      PGRST_JWT_SECRET: YTzAJ1LCmSn49mdLoig4x98SizjaHlXl
      PGRST_SECRET_IS_BASE64: "false"
      PGRST_JWT_AUD: ""
      PGRST_MAX_ROWS: ""
      PGRST_PRE_REQUEST: ""
      PGRST_ROLE_CLAIM_KEY: ".role"
    volumes:
      - ./postgrest-docker/postgrest.conf:/etc/postgrest.conf
      - ./postgrest-docker/seeds.sql:/etc/seeds.sql
